In [132]:
import numpy as np

# Generate random ratings data
n_users = 10
n_items = 5
ratings = np.random.randint(0, 2, size=(n_users, n_items))
""" ratings = np.array([
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 1]
]) """

' ratings = np.array([\n    [0, 1, 0],\n    [0, 1, 1],\n    [1, 0, 1]\n]) '

In [133]:
def cosine_similarity(ratings):
    # Calculate the similarity between items using cosine similarity
    item_similarity = np.dot(ratings.T, ratings)  # Transpose the matrix and compute dot product

    # Normalize the item similarity
    item_norms = np.linalg.norm(ratings, axis=0)
    item_similarity = item_similarity/(item_norms[:,np.newaxis]*item_norms)    
    return item_similarity

In [134]:
# Create a function to make item recommendations
def item_based_recommendation(user_id, ratings, item_similarity, top_n=3):
    user_ratings = ratings[user_id]
    weighted_ratings = np.dot(user_ratings, item_similarity)
    print("Weigthed Ratings")
    print(user_ratings)
    print(weighted_ratings)
    top_item_indices = np.argsort(weighted_ratings)[::-1][:top_n]
    return top_item_indices

In [136]:
# Example: Recommend items for user 0
user_id = np.random.randint(0, ratings.shape[0])
#user_id = 2
item_similarity = cosine_similarity(ratings)
print("Data")
print(ratings)
print("Similarity")
print(item_similarity)
recommended_items = item_based_recommendation(user_id, ratings, item_similarity, top_n=3)
print(f"Recommended items for user {user_id}: {recommended_items}")

Data
[[1 1 1 1 1]
 [1 1 0 1 1]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [1 1 0 1 1]
 [1 0 0 0 0]]
Similarity
[[1.         0.67082039 0.35355339 0.75       0.53033009]
 [0.67082039 1.         0.63245553 0.89442719 0.63245553]
 [0.35355339 0.63245553 1.         0.70710678 0.5       ]
 [0.75       0.89442719 0.70710678 1.         0.70710678]
 [0.53033009 0.63245553 0.5        0.70710678 1.        ]]
Weigthed Ratings
[0 0 0 0 1]
[0.53033009 0.63245553 0.5        0.70710678 1.        ]
Recommended items for user 7: [4 3 1]
